# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 07:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('meerut', django.db.models.manager.Manager()),
            ],
        ),
    ]
