# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171210_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
